image:
  file: .gitpod.dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: initialize DB
    init: bash init_db.sh
  - name: populate DB
      gp sync-done bash -c psql -U dtracy -d eztutor < /workspace/Rust_servers_Apps_Services/tutor_db/src/iter4/database.sql

ports:
  - port: 3000
    onOpen: open-preview

#sh ./scripts/init_db.sh