image:
  file: .gitpod.dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: bash init_db.sh 
# List the ports to expose. Learn ore https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

#sh ./scripts/init_db.sh