image:
  file: .gitpod.dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
#tasks:
#  - name: Start DB
#    init: service postgresql start
#    command: psql -U $DB_USER -d $DB_NAME -f tutor_db/src/iter4/database.sql

# List the ports to expose. Learn ore https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

#sh ./scripts/init_db.sh